### ISSUE TITLE
Yield error on run

### ISSUE THREAD

**Issue by abalter** [iliakan/plunk#20]
I'm running Ubuntu 17.04. 

I installed with `sudo npm install -g plunk`

```
balter@balterbox:~/startbootstrap-agency$ plunk
/usr/local/lib/node_modules/plunk/bin/plunk:19
  let plunkContent = yield* updateDir({
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by Tiaryn** [comment]
Most likely your node.js package is not up to date.

source: https://stackoverflow.com/questions/41960142/block-scoped-declarations-not-yet-supported-outside-strict-mode-laravel-mix
